application: hashtock2
version: 1
runtime: go
api_version: go1

handlers:
- url: /api/_cron/.*
  script: _go_app
  login: admin

- url: /api/.*
  script: _go_app
  login: required

- url: /admin/.*
  script: _go_app
  login: admin

cron:
- description: Bank orders
  url: /api/_cron/bank-orders/
  schedule: every 5 minutes
