application: hashtock
version: 1-3
runtime: go
api_version: go1

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /static/
  static_dir: static/

- url: /_cron/.*
  script: _go_app
  login: admin

- url: /api/.*
  script: _go_app
  login: required

- url: /auth/.*
  script: _go_app

- url: /admin/.*
  script: _go_app
  login: admin
